Repository vinhloc30796/creativecontact-app, pull requests merged in 2024-12, with the labels that each got.

#130 refactor(profile): fix warning: passing promises & async in /profile
  app/(protected)/profile/AnonymousProfilePage.tsx
  app/(protected)/profile/ErrorPortfolioProjectCard.tsx
  app/(protected)/profile/ErrorProfileCard.tsx
  app/(protected)/profile/PortfolioSection.tsx
  app/(protected)/profile/ProfileDataContext.tsx
  app/(protected)/profile/page.tsx
  components/contacts/ContactCard.tsx
  components/contacts/ContactList.tsx
  components/contacts/ErrorContactCard.tsx
  components/profile/ProfileCard.tsx
  components/wrappers/ErrorBoundary.tsx
  next.config.mjs
  public/translations/en/ContactList.json
  public/translations/en/ProfilePage.json
  public/translations/vi/ContactList.json
  public/translations/vi/ProfilePage.json
  utils/user_name.ts
Labels: bug, enhancement

#131 feat(profile)!: implement streaming SSR for portfolio data
  app/(auth)/logout/page.tsx
  app/(protected)/profile/PortfolioSection.tsx
  app/(protected)/profile/page.tsx
  app/api/user/[id]/contacts/route.ts
  app/api/user/[id]/portfolio-artworks/helper.ts
  components/contacts/ContactList.tsx
  components/profile/ProfileCard.tsx
Labels: enhancement

#132 perf(profile): remove unneeded delays in portfolio data fetching; translate logout
  app/(auth)/logout/page.tsx
  app/(protected)/profile/page.tsx
  app/api/user/[id]/portfolio-artworks/helper.ts
  components/contacts/ErrorContactCard.tsx
  public/translations/en/ContactList.json
  public/translations/en/LogoutPage.json
  public/translations/vi/ContactList.json
  public/translations/vi/LogoutPage.json
Labels: bug, enhancement

#123 feat(portfolio): enable save button behavior
  app/(protected)/portfolio/[artworkId]/PortfolioEditForm.tsx
  app/actions/artwork/writeArtworkInfo.ts
  app/actions/user/writeUserInfo.ts
  components/artwork/ArtworkInfoStep.tsx
  drizzle/schema/artwork.ts
  services/artwork-service.ts
  services/user-service.ts
Labels: enhancement

#125 feat(createPortfoilo): implement create portfolio page WEB-227
  app/(protected)/portfolio/new/PortfolioCreateForm.tsx
  app/(protected)/portfolio/new/action.client.ts
  app/(protected)/portfolio/new/add_coowner.component.tsx
  app/(protected)/portfolio/new/files_uplooad_provider.component.tsx
  app/(protected)/portfolio/new/media.component.tsx
  app/(protected)/portfolio/new/media_upload.component.tsx
  app/(protected)/portfolio/new/page.tsx
  app/(protected)/portfolio/new/portfolio_create_card.component.tsx
  app/(protected)/portfolio/new/transaction.actions.ts
  app/(protected)/portfolio/new/upload_info.component.tsx
  app/(protected)/portfolio/new/wrapper.component.tsx
  components/artwork/ArtworkCreditInfoStep.tsx
  components/uploads/media-upload.tsx
  public/translations/en/ArtworkCreditInfoStep.json
  public/translations/en/Portfolio.json
  public/translations/en/credit-info.json
  public/translations/en/media-upload.json
  public/translations/vi/ArtworkCreditInfoStep.json
  public/translations/vi/Portfolio.json
  public/translations/vi/credit-info.json
  public/translations/vi/media-upload.json
Labels: enhancement

#126 feat(portfolio): delete portfolio WEB-226
  app/(protected)/profile/PortfolioTabs.tsx
  app/actions/portfolio/client.actions.ts
  app/actions/portfolio/server.action.ts
Labels: enhancement

#133 feat(portfolio): add upload progress tracking
  app/(protected)/portfolio/new/action.client.ts
  app/(protected)/portfolio/new/portfolio_create_card.component.tsx
Labels: enhancement

#134 refactor(upload): consolidate upload logic and fix asset ID handling
  app/(protected)/portfolio/[artworkId]/PortfolioEditForm.tsx
  app/(protected)/portfolio/new/action.client.ts
  app/(protected)/portfolio/new/portfolio_create_card.component.tsx
  app/(protected)/portfolio/new/transaction.actions.ts
  app/(public)/event/[eventSlug]/upload/client.ts
Labels: documentation, enhancement

#141 feat!: upgrade to NextJS 15 & React 19
  app/(auth)/logout/page.tsx
  app/(auth)/signout/route.ts
  app/(auth)/signup/page.tsx
  app/(protected)/portfolio/[artworkId]/action.ts
  app/(protected)/portfolio/[artworkId]/page.tsx
  app/(protected)/portfolio/new/page.tsx
  app/(protected)/portfolio/new/portfolio_create_card.component.tsx
  app/(protected)/profile/AnonymousProfilePage.tsx
  app/(protected)/profile/edit/page.tsx
  app/(protected)/profile/page.tsx
  app/(public)/(event)/api/event-artworks/route.ts
  app/(public)/(event)/api/events/[slug]/route.ts
  app/(public)/(event)/register/_sections/RegistrationForm.tsx
  app/(public)/(event)/register/_sections/_register.tsx
  app/(public)/(event)/register/page.tsx
  app/(public)/event/[eventSlug]/EventEnded.tsx
  app/(public)/event/[eventSlug]/UploadStatistics.tsx
  app/(public)/event/[eventSlug]/artwork/[artworkId]/page.tsx
  app/(public)/event/[eventSlug]/page.tsx
  app/(public)/event/[eventSlug]/upload-confirmed/page.tsx
  app/(public)/event/[eventSlug]/upload/UploadPageClient.tsx
  app/(public)/event/[eventSlug]/upload/page.tsx
  app/api/artworks/[id]/assets/route.ts
  app/api/artworks/[id]/credits/route.ts
  app/api/artworks/[id]/route.ts
  app/api/user/[id]/contacts/route.ts
  app/api/user/[id]/portfolio-artworks/route.ts
  app/api/user/[id]/route.ts
  app/layout.tsx
  app/page.tsx
  components/InConstruction.tsx
  components/UnderConstruction.tsx
  components/branding/EventLogo.tsx
  components/ui/calendar.tsx
  components/user/ContactInfoStep.tsx
  components/user/ProfessionalInfoStep.tsx
  components/wrappers/EventFooter.tsx
  components/wrappers/EventHeader.tsx
  components/wrappers/LoadingUserHeader.tsx
  components/wrappers/UserHeader.tsx
  hooks/useServerAuth.ts
  lib/i18n/init-server.ts
  lib/i18n/settings.ts
  next.config.ts
  package-lock.json
  package.json
  pnpm-lock.yaml
  tsconfig.json
  types/svg.d.ts
  utils/supabase/server.ts
Labels: dependency

#137 fix(portfolio): Redirect user back to /profile after successful project creation
  app/(protected)/portfolio/new/portfolio_create_card.component.tsx
Labels: bug

#138 feat(portfolio): calculate and display user's total data usage
  app/(protected)/portfolio/[artworkId]/PortfolioEditForm.tsx
  app/(protected)/portfolio/[artworkId]/page.tsx
  app/(protected)/portfolio/new/PortfolioCreateForm.tsx
  app/(public)/event/[eventSlug]/upload/UploadPageClient.tsx
  app/api/user/[id]/portfolio-artworks/helper.ts
  components/uploads/DataUsage.tsx
  components/uploads/media-upload.tsx
Labels: enhancement

#128 fix(portfolio): correct display of existing artworks count
  app/(protected)/portfolio/[artworkId]/PortfolioEditForm.tsx
  app/api/artworks/by-uploader/route.ts
  components/artwork/ArtworkInfoStep.tsx
Labels: bug

#145 fix(auth): prevent double-firing on /logout and /signout
  app/(auth)/logout/page.tsx
  app/(auth)/signout/route.ts
Labels: bug
