Repository vinhloc30796/creativecontact-app, pull requests merged in 2024-11, with the labels that each got.

#114 fix(db): add user_name column to user_infos seed data
  supabase/seed.sql
Labels: bug

#113 feat(portfolio): change the layout in Portfolio Edit page and make media vertically scrollable
  app/(protected)/portfolio/[artworkId]/PortfolioEditForm.tsx
  app/(protected)/portfolio/new/PortfolioCreateForm.tsx
  app/(protected)/profile/PortfolioSection.tsx
  app/(protected)/profile/PortfolioTabs.tsx
  app/(protected)/profile/page.tsx
  components/uploads/DataUsage.tsx
  components/uploads/media-upload.tsx
  public/translations/en/Portfolio.json
  stores/usePendingSizeStore.ts
Labels: enhancement, style

#115 refactor(profile): move ProfileCard to dedicated component & restyle
  app/(protected)/profile/page.tsx
  components/profile/ProfileCard.tsx
  lib/phone.ts
Labels: documentation, style

#116 feat(profile): update profile changes to database
  app/(protected)/profile/page.tsx
  app/actions/user/writeUserInfo.ts
  package-lock.json
  services/user-service.ts
Labels: enhancement

#117 feat(profile)!: implement unified industry-experience UI
  app/(auth)/signup/page.tsx
  app/(protected)/profile/page.tsx
  app/(public)/(event)/api/event-artworks/helper.ts
  app/(public)/(event)/api/event-artworks/route.ts
  app/(public)/(event)/api/events/[slug]/helper.ts
  app/(public)/(event)/api/events/[slug]/route.ts
  app/(public)/(event)/api/recent-events/helper.ts
  app/(public)/(event)/api/recent-events/route.ts
  app/(public)/(event)/register/_sections/ProfessionalInfoForm.tsx
  app/(public)/(event)/register/_sections/RegistrationForm.tsx
  app/(public)/(event)/register/_sections/formSchema.ts
  app/(public)/(event)/register/_sections/types.ts
  app/(public)/(event)/register/types.ts
  app/(public)/event/[eventSlug]/page.tsx
  app/(public)/event/[eventSlug]/upload/UploadPageClient.tsx
  app/(public)/event/[eventSlug]/upload/client-helpers.ts
  app/actions/user/writeUserInfo.ts
  app/api/user/[id]/contacts/helper.ts
  app/api/user/[id]/helper.ts
  app/api/user/helper.ts
  app/form-schemas/about-info.ts
  app/form-schemas/professional-info.ts
  app/types/UserInfo.tsx
  components/contacts/ContactCard.tsx
  components/contacts/ContactList.tsx
  components/profile/ProfessionalSection.tsx
  components/profile/ProfileCard.tsx
  components/ui/combo-badge.tsx
  components/user/ProfessionalInfoStep.tsx
  drizzle/schema/user.ts
  services/user-service.ts
  supabase/migrations/20241123044655_connect_industry_and_seniority.sql
  supabase/seed.sql
Labels: bug, documentation, enhancement, style

#120 feat(i18n): fix language detection middleware & profile translations
  app/(auth)/login/page.tsx
  app/(auth)/logout/page.tsx
  app/(auth)/signout/route.ts
  app/(protected)/profile/PortfolioSection.tsx
  app/(protected)/profile/PortfolioSectionSkeleton.tsx
  app/(protected)/profile/PortfolioTabs.tsx
  app/(protected)/profile/page.tsx
  app/(public)/(event)/api/event-artworks/route.ts
  app/(public)/(event)/api/magic-link/route.ts
  app/(public)/(event)/api/recent-events/route.ts
  app/(public)/(event)/checkin/_utils/apiHelpers.ts
  app/(public)/(event)/checkin/page.tsx
  app/layout.tsx
  app/providers.tsx
  components/auth/MagicSignIn.tsx
  components/contacts/ContactCard.tsx
  components/contacts/ContactList.tsx
  components/contacts/ContactListSkeleton.tsx
  components/contacts/EmptyContactCard.tsx
  components/profile/ProfileCard.tsx
  components/profile/ProfileCardSkeleton.tsx
  hooks/useServerAuth.ts
  lib/i18n/init-client.ts
  lib/i18n/init-server.ts
  middleware.ts
  next.config.mjs
  package.json
  pnpm-lock.yaml
  public/early-access-2024-background-blur.png
  public/translations/en/ContactCard.json
  public/translations/en/ProfileCard.json
  public/translations/en/ProfilePage.json
  public/translations/en/auth.json
  public/translations/vi/ContactCard.json
  public/translations/vi/ProfileCard.json
  public/translations/vi/ProfilePage.json
  public/translations/vi/auth.json
  utils/middleware/i18n-middleware.ts
  utils/middleware/i18next-middleware.ts
  utils/middleware/lang-persist.ts
  utils/placeholder.ts
  utils/profile_image.ts
  utils/supabase/middleware.ts
  utils/user_name.ts
Labels: bug, enhancement, dependency, style

#124 add seed data for artwork assets
  supabase/seed.sql
Labels: documentation, enhancement

#127 refactor!: replace external SVG import with inline SVG in CreativeCon…
  components/branding/CreativeContactLogo.tsx
  next.config.mjs
  package.json
  pnpm-lock.yaml
Labels: bug, style
