Repository vinhloc30796/creativecontact-app, pull requests merged in 2025-05, with the labels that each got.

#156 feat(auth): implement Discord-based staff approval workflow
  .env.example
  .env.local.example
  app/actions/auth/logoutStaff.ts
  app/actions/auth/prevalidateStaff.ts
  app/actions/auth/staff.ts
  app/api/discord/interactions/route.ts
  app/api/discord/notify-signup/route.ts
  app/api/staff/approval/approve/[userId]/route.ts
  app/api/staff/approval/reject/[userId]/route.ts
  app/collections/Events.ts
  app/collections/Media.ts
  app/collections/Posts.ts
  app/collections/Staffs.ts
  app/collections/access/canManageContent.ts
  app/staff/login/page.tsx
  app/staff/signup/page.tsx
  app/staff/signup/pending-approval/page.tsx
  app/staff/signup/types.ts
  emails/templates/StaffApproved.tsx
  package.json
  payload-types.ts
  pnpm-lock.yaml
  supabase/payload-migrations/20250508_084716_add_staff_approval_status.json
  supabase/payload-migrations/20250508_084716_add_staff_approval_status.ts
  supabase/payload-migrations/index.ts
  utils/discord_verify.ts
Labels: bug, documentation, enhancement

#157 fix(discord/staffs): add timeout & better error logging
  app/api/discord/interactions/route.ts
Labels: bug

#158 fix(discord/debug): add more debugging for /interactions
  app/api/discord/interactions/route.ts
Labels: bug

#159 fix(build): document S3 env vars; add even more debug logging
  .env
  lib/payload/getCustomPayload.ts
Labels: bug, deployment

#160 fix(build/payload-cms): use vercelAdapter for serverless functions
  app/payload.config.ts
Labels: bug, dependency, deployment

#161 fix(payload-cms): thread NextJS request through to Payload CMS
  app/api/discord/interactions/route.ts
Labels: bug, deployment

#163 fix(discord/payload-cms): simplify by skip fetching Staffs
  app/api/discord/interactions/route.ts
Labels: bug

#165 feat(events): display upcoming events in event ticker
  README.md
  app/page.tsx
  lib/dateUtils.ts
  public/translations/en/HomePage.json
  public/translations/vi/HomePage.json
  supabase/20240610094940_create_schemas.sql
Labels: enhancement, good first issue
